apiVersion: v1
kind: PersistentVolume
metadata:
  name: quantum-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual   # ✅ ADD THIS
  hostPath:
    path: /mnt/data
