apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quantum-pvc
  namespace: quantumapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual   # ✅ ADD THIS
  resources:
    requests:
      storage: 1Gi
