apiVersion: v1
kind: Service
metadata:
  name: quantum-service
  namespace: quantumapp
spec:
  type: ClusterIP   # ✅ CHANGE
  selector:
    app: quantum-app
  ports:
    - port: 8000
      targetPort: 8000
